on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Check out the repository
    - name: Check out repository
      uses: actions/checkout@v3

    # Step 2: Set up Python environment
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.9

    # Step 3: Install dependencies
    - name: Install dependencies
      run: |
        pip install --no-cache-dir -r requirements.txt
        pip install pyinstaller

    # Step 4: Debug directory structure to confirm app.py exists
    - name: Debug repository structure
      run: |
        echo "Current Working Directory:"
        pwd
        echo "Repository Structure:"
        ls -R .

    # Step 5: Build the executable
    - name: Build LeadgerDesktop executable
      run: |
        TIMESTAMP=$(date +'%Y%m%d%H%M%S')  # Generate timestamp
        FOLDER_NAME="package_${TIMESTAMP}"  # Folder name with timestamp
        EXECUTABLE_NAME="LeadgerDesktop.${TIMESTAMP}.v2"  # Executable name with timestamp
        pyinstaller --onefile --name=${EXECUTABLE_NAME} --noconsole \
        --add-data "templates:templates" \
        --add-data "instance:instance" \
        --icon=LeadgerApp/icon.ico app.py
        mv dist "${FOLDER_NAME}"  # Rename dist to package_timestamp

    # Optional Step 7: Push the executable back to the repository (if needed)
    - name: Commit and push executable
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git add ${FOLDER_NAME}/*
        git commit -m "Build and Package LeadgerApp: Added ${EXECUTABLE_NAME} executable"
        git push "https://${GITHUB_TOKEN}@github.com/prasad3936/LeadgerApp.git" HEAD:main
