name: Build and Release LeadgerApp

on:
  push:
    branches:
      - main

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Check out the repository
    - name: Check out repository
      uses: actions/checkout@v3

    # Step 2: Set up Python environment
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.9

    # Step 3: Install dependencies
    - name: Install dependencies
      run: |
        pip install --no-cache-dir -r requirements.txt
        pip install pyinstaller

    # Step 4: Debug directory structure to confirm app.py exists
    - name: Debug repository structure
      run: |
        echo "Current Working Directory:"
        pwd
        echo "Repository Structure:"
        ls -R .

    # Step 5: Build the executable
    - name: Build LeadgerDesktop executable
      run: |
        TIMESTAMP=$(date +'%Y%m%d%H%M%S')
        pyinstaller --onefile --name=LeadgerDesktop.$TIMESTAMP --noconsole \
        --add-data "templates:templates" \
        --add-data "instance:instance" \
        --icon=LeadgerApp/icon.ico app.py
        cp -r instance dist/instance
        mv dist LeadgerDesktop_$TIMESTAMP
        tar -czf LeadgerDesktop_$TIMESTAMP.tar.gz LeadgerDesktop_$TIMESTAMP

    # Step 6: Create a new release and upload the package
    - name: Create GitHub Release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: LeadgerDesktop_$(date +'%Y%m%d%H%M%S')
        release_name: LeadgerDesktop_$(date +'%Y%m%d%H%M%S')
        draft: false
        prerelease: false

    - name: Upload Release Asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create-release.outputs.upload_url }}
        asset_path: ./LeadgerDesktop_$(date +'%Y%m%d%H%M%S').tar.gz
        asset_name: LeadgerDesktop_$(date +'%Y%m%d%H%M%S').tar.gz
        asset_content_type: application/gzip
