name: Build and Release

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Check out the repository
    - name: Check out repository
      uses: actions/checkout@v3

    # Step 2: Set up Python environment
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.9

    # Step 3: Install dependencies
    - name: Install dependencies
      run: |
        pip install --no-cache-dir -r requirements.txt
        pip install pyinstaller

    # Step 4: Build the executable
    - name: Build LeadgerDesktop executable
      run: |
        pyinstaller --onefile --name=LeadgerDesktop.1.$(date +'%Y%m%d%H%M%S') --noconsole \
        --add-data "templates:templates" \
        --add-data "instance:instance" \
        --icon=LeadgerApp/icon.ico app.py
        cp -r instance dist/instance
        mv dist   LeadgerDesktop_$(date +'%Y%m%d%H%M%S') # Rename dist to package_timestamp
        
    # Step 5: Create a tag (if not exists) and push it
    - name: Create and push tag
      run: |
        current_version=$(git describe --tags --abbrev=0 || echo "v0.0.0")

        if [ "$current_version" == "v0.0.0" ]; then
          new_version="v1.0.0"
        else
          new_version=$(echo $current_version | awk -F. -v OFS=. '{$NF++;print}')
        fi

        echo "Creating new tag: $new_version"
        
        git tag $new_version
        git push origin $new_version

    # Step 6: Upload release artifacts
    - name: Upload release
      uses: softprops/action-gh-release@v1
      with:
        files: LeadgerDesktop_*/**
        tag_name: ${{ steps.create_and_push_tag.outputs.new_version }}  # Pass the created tag
        token: ${{ secrets.GITHUB_TOKEN }}
