on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        pip install --no-cache-dir -r requirements.txt
        pip install pyinstaller

    - name: Build LeadgerDesktop executable
      run: |
        EXECUTABLE_NAME="LeadgerDesktop.$(git rev-parse --short HEAD)"
        pyinstaller --onefile --name=${EXECUTABLE_NAME} --noconsole \
        --add-data "templates:templates" \
        --add-data "instance:instance" \
        --icon=LeadgerApp/icon.ico app.py
        cp -r instance dist/instance
        mv dist "${EXECUTABLE_NAME}"

    - name: Compress build folder into a .zip file
      run: |
        EXECUTABLE_NAME="LeadgerDesktop.$(git rev-parse --short HEAD)"
        zip -r "${EXECUTABLE_NAME}.zip" "${EXECUTABLE_NAME}"

    - name: Upload release asset
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        EXECUTABLE_NAME="LeadgerDesktop.$(git rev-parse --short HEAD)"
        curl -XPOST -H "Authorization: token $GITHUB_TOKEN" \
          -d '{"tag_name": "'${EXECUTABLE_NAME}'", "name": "'${EXECUTABLE_NAME}'", "body": "Automated release"}' \
          "https://api.github.com/repos/${{ github.repository }}/releases"
        
        # Upload the .zip file as release asset
        RELEASE_ID=$(curl -s -H "Authorization: token $GITHUB_TOKEN" \
          "https://api.github.com/repos/${{ github.repository }}/releases/tags/${EXECUTABLE_NAME}" | jq .id)

        curl -XPOST -H "Authorization: token $GITHUB_TOKEN" \
          -H "Content-Type: application/zip" \
          --data-binary @"${EXECUTABLE_NAME}.zip" \
          "https://uploads.github.com/repos/${{ github.repository }}/releases/$RELEASE_ID/assets?name=${EXECUTABLE_NAME}.zip"
