name: Release Workflow

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Check out the repository
    - name: Check out repository
      uses: actions/checkout@v3

    # Step 2: Configure Git
    - name: Configure Git
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"

    # Step 3: Get the latest tag
    - name: Get latest tag
      id: get_tag
      run: |
        TAG=$(git describe --tags $(git rev-list --tags --max-count=1) 2>/dev/null || echo "")
        if [ -z "$TAG" ]; then
          echo "tag=none" >> $GITHUB_ENV
        else
          echo "tag=$TAG" >> $GITHUB_ENV
        fi

    # Step 4: Calculate next version
    - name: Calculate next version
      id: calculate_version
      run: |
        if [ "${{ env.tag }}" = "none" ]; then
          echo "next_version=v1.0.0" >> $GITHUB_ENV
        else
          # Remove 'v' prefix and split into major, minor, patch
          TAG="${{ env.tag#v }}"
          IFS='.' read -r major minor patch <<< "$TAG"
          patch=$((patch + 1))  # Increment patch version
          echo "next_version=v$major.$minor.$patch" >> $GITHUB_ENV
        fi
      env:
        tag: ${{ env.tag }}

    # Step 5: Create and push the tag
    - name: Create and push new tag
      run: |
        git tag -a ${{ env.next_version }} -m "Release ${{ env.next_version }}"
        git push origin ${{ env.next_version }}

    # Step 6: Build LeadgerDesktop executable
    - name: Build LeadgerDesktop executable
      run: |
        mkdir -p LeadgerDesktop_${{ env.next_version }}
        pyinstaller --onefile --name=LeadgerDesktop --noconsole \
        --add-data "templates:templates" \
        --add-data "instance:instance" \
        --icon=LeadgerApp/icon.ico app.py
        cp -r instance dist/instance
        mv dist/* LeadgerDesktop_${{ env.next_version }}

    # Step 7: Create GitHub release
    - name: Create GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        files: LeadgerDesktop_${{ env.next_version }}/*
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
