name: Build and Release LeadgerDesktop

on:
  push:
    branches:
      - main

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Check out the repository
    - name: Check out repository
      uses: actions/checkout@v3

    # Step 2: Set up Python environment
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.9

    # Step 3: Install dependencies
    - name: Install dependencies
      run: |
        pip install --no-cache-dir -r requirements.txt
        pip install pyinstaller

    # Step 4: Build the executable
    - name: Build LeadgerDesktop executable
      id: build
      run: |
        TIMESTAMP=$(date +'%Y%m%d%H%M%S')
        echo "timestamp=${TIMESTAMP}" >> $GITHUB_ENV

        EXECUTABLE_NAME="LeadgerDesktop.${TIMESTAMP}"
        pyinstaller --onefile --name="${EXECUTABLE_NAME}" --noconsole \
        --add-data "templates:templates" \
        --add-data "instance:instance" \
        --icon=LeadgerApp/icon.ico app.py

        cp -r instance dist/instance
        mv dist "LeadgerDesktop_${TIMESTAMP}"

    # Step 5: Create and push a Git tag
    - name: Create and push a Git tag
      env:
        TIMESTAMP: ${{ env.timestamp }}
      run: |
        TAG_NAME="v${TIMESTAMP}"
        echo "Creating Git tag: ${TAG_NAME}"
        
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        
        git tag "${TAG_NAME}"
        git push origin "${TAG_NAME}"

        # Verify tags on remote
        echo "Remote tags after push:"
        git ls-remote --tags origin

    # Step 6: Create a GitHub release
    - name: Create GitHub release
      uses: softprops/action-gh-release@v1
      with:
        files: LeadgerDesktop_${{ env.timestamp }}/*
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    # Step 7: Clean up temporary files
    - name: Clean up
      run: |
        rm -rf LeadgerDesktop_${{ env.timestamp }}
