name: Simple Versioning Release

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Check out the repository
    - name: Check out repository
      uses: actions/checkout@v3

    # Step 2: Configure Git
    - name: Configure Git
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"

    # Step 3: Get latest tag or create v1.0.0 if no tags exist
    - name: Get latest tag and increment
      id: get_tag
      run: |
        # Get the latest tag or set "none" if no tags exist
        TAG=$(git describe --tags $(git rev-list --tags --max-count=1) 2>/dev/null || echo "none")

        # If no tags exist, set to v1.0.0
        if [ "$TAG" = "none" ]; then
          echo "next_version=v1.0.0" >> $GITHUB_ENV
        else
          # Remove 'v' prefix and increment the patch version
          TAG="${TAG#v}"
          IFS='.' read -r major minor patch <<< "$TAG"
          patch=$((patch + 1))
          echo "next_version=v$major.$minor.$patch" >> $GITHUB_ENV
        fi

    # Step 4: Create and push the new tag
    - name: Create and push new tag
      run: |
        git tag -a ${{ env.next_version }} -m "Release ${{ env.next_version }}"
        git push origin ${{ env.next_version }}

    # Step 5: (Optional) Build and release your app
    - name: Build LeadgerDesktop executable
      run: |
        # Your build commands here, e.g., using pyinstaller
        echo "Building and packaging LeadgerDesktop for version ${{ env.next_version }}"
      
    # Step 6: (Optional) Create GitHub Release
    - name: Create GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        files: path/to/your/executable/*  # Specify your file path
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
